### ISSUE TITLE
Releasing WebJar

### ISSUE THREAD

**Issue by agebhar1** [Product-Foundry/hal-browser-webjar#1]
@andrekampert 

thanks for packing the HAL Browser as WebJar. Could you please start a release request (http://www.webjars.org/contributing) to add this WebJar to webjars.org. So it's listed and published on Maven Central. Thanks.

**Comment by andrekampert** [comment]
Created at https://github.com/webjars/webjars/issues/946

**Comment by agebhar1** [comment]
Thanks @andrekampert
