### ISSUE TITLE
Configuring entryPoint when using webjar

### ISSUE THREAD

**Issue by tommyb82** [Product-Foundry/hal-browser-webjar#2]
I'm now pulling in the new webjar (http://mvnrepository.com/artifact/org.webjars/hal-browser/b7669f1-1) into a Spring Boot / HATEOAS web service app and it works great..
However - the default entryPoint as configured in browser.html ('/') means that when I access the browser it doesn't see the application's true entry point (i.e. the context path) until I manually enter it.

I would appreciate any advice / workarounds that may be possible for this - obviously I don't want to unjar - hack - rejar to change any files as that would defeat the purpose of pulling it in as a webjar in the first place!

Thanks for the excellent work.

**Comment by andrekampert** [comment]
Sorry for the late reply. The WebJar directly packages https://github.com/mikekelly/hal-browser without modifications. Referring to https://github.com/mikekelly/hal-browser/issues/53 I believe the correct way to do this is to add a hash to the browser url, e.g.

```
http://haltalk.herokuapp.com/explorer/browser.html#http://localhost:3000
```

**Comment by tommyb82** [comment]
Thanks for the reply, yes we had discovered that feature and it provides a satisfactory workaround to get the user into the HAL browser in the right place initially, the only issue is if they then click the 'Go to Entry point' button, it drops them back at the web root. We could add a redirect in to deal with this situation though I think.  Thanks for your advice and for getting the webjar for this setup!
